a = input('digite algo: ')
print('o tipo primitivo desse valor e: ', type(a))
print('so tem espacos: ', a.isspace())
print('e um numero: ', a.isnumeric())
print('e alfanumerico: ', a.isalnum())
print('e alfabetico?', a.isalpha())
print('esta em maiuscula? ', a.isupper())
print('esta em minusculo? ', a.islower())
print('esta capitalizada? ', a.istitle())