print("Digite uma medida em metro e transforme em centimetro: ")
n = int(input('qual medida voce deseja ? \n'))
soma = (n * 100)
print('Essa medida transformada da :')
print('{} centimetros'.format(soma))