n = int(input('quanto voce ganha por hora no mês ? \n'))
s = int(input('Quantas horas voce trabalha por mês  \n'))
salario = (s * n)
descont = ( salario - 0.11)
desconto2 = (salario - 0.08)
desconto3 = (salario - 0.05) 
print("Seu salario sem desconto é:")
print(salario)
print("Seu salario com os descontos do imposto de renda é {}".format(descont))
print("Seu salario com os descontos do INSS é {}".format(desconto2))
print("Seu salario com os descontos do sindicato é {}".format(desconto3))
